### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by markamodo** [dancapper/gmailArchiveScript#1]
Here's the smallest issue ever 😄 there's a typo on the below line (`temrs` should be `terms`). Thanks for the script! Still configuring it but seems like it'll really nice.

https://github.com/dancapper/gmailArchiveScript/blob/f9a5415fc5f8cefae121fe8cd1f532793732827f/gmailAutoArchive.gs#L41

**Comment by dancapper** [comment]
Nice spotting! Let me know if you find any other issues, hope it is helpful for you.
